POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Me tengo que subscribir a midudev en Youtube",
    "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json
